version: "2.1"
services:
  # Kafka/Zookeeper container
  docker-kafka:
    image: krisgeus/docker-kafka
    container_name: docker-kafka
    environment:
      - ADVERTISED_HOST=docker-kafka
      - LOG_RETENTION_HOURS=1
      - AUTO_CREATE_TOPICS=false
      - KAFKA_CREATE_TOPICS=divolte:4:1
    ports:
      - 9092:9092 # kafka broker
      - 2181:2181 # Zookeeper
  # Divolte container
  docker-divolte:
    image: divolte_docker-divolte
    container_name: docker-divolte
    environment:
      - DIVOLTE_KAFKA_BROKER_LIST=docker-kafka:9092
    volumes:
      - ./conf/divolte/:/opt/divolte/divolte-collector-0.5.0/conf/
    ports:
      - 8290:8290
    depends_on:
      - docker-kafka
    links:
      - docker-kafka:docker-kafka
  # Druid container
  docker-druid:
    build: druid/
    container_name: docker-druid
    ports:
      - 8081:8081
      - 8082:8082
    depends_on:
      - docker-kafka
    links:
      - docker-kafka:docker-kafka
  # Superset container
  docker-superset:
    image: amancevice/superset
    container_name: docker-superset
    ports:
      - 8088:8088
    links:
      - docker-druid:docker-druid
  # Superset container
  docker-app:
    build: app/
    container_name: docker-app
    ports:
      - 8090:8090
